# Generated by Django 4.1.7 on 2023-03-05 20:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0005_websiteinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="websiteinfo",
            name="about",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="websiteinfo",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
